kind: ConfigMap  
apiVersion: v1  
metadata:  
  name: webconfigconfigmap-web-config  
  labels:  
    app: webconfigconfigmap   
data:  
  Web.config: |  
    <?xml version="1.0" encoding="utf-8"?>

    <configuration>
      <appSettings>
        <add key="ConfigPulledFrom" value="a K8s ConfigMap"/>
      </appSettings>
      <connectionStrings/>
      <system.web>
      </system.web>
    </configuration>
